### ISSUE TITLE
release checklist

### ISSUE THREAD

**Issue by jmoiron** [jmoiron/quantum-skies#1]
gregification:

 - [x] laserIO
 - [ ] tempad
 - [x] ender storage (rebalance)
 - [x] colossal chests
 - [x] tom's storage

questbook

- [x] placeholders for iv/luv/zpm/uv

admin

- [x] test cf build (embed gtec?)
- [ ] test server files build
- [x] overrides (defaultconfig) vs hard overrides (for better pack updating)
