### ISSUE TITLE
0.3.5 todo

### ISSUE THREAD

**Issue by jmoiron** [jmoiron/quantum-skies#16]
- [x] recipe for the color applicator
- [x] recipe for moss + sieve recipe for flowers
- [x] alternative for ink sacks (right now you can use the fisher if you are not in a squid spawning biome)
- [x] vegan/peaceful option for leather (for backpacks)
- [x] enviromat fixes (dye color tags for recipes, chem bath dying for alabaster)
- [x] remove epoxy requirement from pre-moon mats (add glue alts)
- [x] restore simple hatch/bus recipes for ULV machines
