### ISSUE TITLE
0.3.7 todo

### ISSUE THREAD

**Issue by jmoiron** [jmoiron/quantum-skies#18]
- [x] remove epoxy sheet as a requirement for the fiberglass pulp quest
- [x] adjust glue fiberglass recipe speed and/or yield (right now it takes ~5h20m to craft a set of space gear)
- [x] VAB should migrate off of solid steel machine casing, which requires a tool to make and is not used by anything in base GT
- [x] airlock door needs a recipe

**Comment by jmoiron** [comment]
gcyr bug..  server only?:

![2024-09-27_23 25 34](https://github.com/user-attachments/assets/f6b457cd-e65a-46db-b573-fd923f747e2a)
